language: python
python:
  - "3.12"

install:
  - pip install -r requirements.txt
  - pip install coverage

before_script:
  - python server.py & 
  - echo $! > server_pid.txt

script:
 script:
  - echo $PATH
  - which coverage
  - coverage run --source=chat -m unittest tests.test_chat

after_script:
  - kill $(cat server_pid.txt) 

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cat .coverage
