language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - python server.py & 
  - echo $! > server_pid.txt

script:
  - python -m unittest tests.test_chat

after_script:
  - kill $(cat server_pid.txt) 

