language: python
python:
  - "3.8"

before_install:
  - pip install -r requirements.txt  # Instala las dependencias

before_script:
  - pkill -f "python server.py" || true  # Detiene el servidor si ya está en ejecución
  - echo $! > server_pid.txt  # Guarda el PID

after_script:
  - kill $(cat server_pid.txt)  # Detiene el servidor usando el PID guardado

script:
  - python -m unittest tests.test_chat
