language: python
python:
  - "3.8"

before_install:
  - pip install -r requirements.txt  # Instala las dependencias

before_script:
  - python server.py &  # Inicia el servidor en segundo plano

after_script:
  - kill $(cat server_pid.txt)  # Detiene el servidor usando el PID guardado

script:
  - python -m unittest tests.test_chat
