language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - docker build -t chat-app .
  - docker run -d --name chat-server chat-app

script:
  - docker exec chat-server python -m unittest tests.test_chat
