language: python
python:
  - "3.8"

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - echo "Running unit tests..."
  - python -m unittest tests.test_chat
  - echo "Stopping Docker container..."
  - docker stop chat-server-container

timeout: 20m